### ISSUE TITLE
padding <virtual-scroller> requires sizing children accordingly

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-scroller#77]
`<virtual-scroller>` positions children with `position: absolute` and sets their `width: 100%`, so if the virtual-scroller has padding, children would effectively get the total width of their container (padding included). The user would have to handle that e.g. like this:
```css
virtual-list {
  padding: 10px;
}
virtual-list > * {
  width: calc(100% - 20px);
}
```

See if we can do something to handle padding too, or at least document this limitation
